src/Entity/Address.php
<?php

namespace App\Entity;

use App\Repository\AddressRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: AddressRepository::class)]
class Address
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $city;

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'address')]
    private $user;

    #[ORM\Column(type: 'string', length: 255)]
    private $address;

    #[ORM\Column(type: 'integer')]
    private $cp;

    #[ORM\Column(type: 'string', length: 255)]
    private $address_name;

    #[ORM\OneToMany(mappedBy: 'shipping', targetEntity: Order::class)]
    private $orders;

    public function __construct()
    {
        $this->orders = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getCp(): ?int
    {
        return $this->cp;
    }

    public function setCp(int $cp): self
    {
        $this->cp = $cp;

        return $this;
    }

    public function getAddressName(): ?string
    {
        return $this->address_name;
    }

    public function setAddressName(string $address_name): self
    {
        $this->address_name = $address_name;

        return $this;
    }

    /**
     * @return Collection|Order[]
     */
    public function getOrders(): Collection
    {
        return $this->orders;
    }

    public function addOrder(Order $order): self
    {
        if (!$this->orders->contains($order)) {
            $this->orders[] = $order;
            $order->setShipping($this);
        }

        return $this;
    }

    public function removeOrder(Order $order): self
    {
        if ($this->orders->removeElement($order)) {
            // set the owning side to null (unless already changed)
            if ($order->getShipping() === $this) {
                $order->setShipping(null);
            }
        }

        return $this;
    }

    public function __toString(){
        return $this->address;
    }

}

src/Controller/UserPageController.php
<?php

namespace App\Controller;

use App\Entity\Address;
use App\Entity\OrderItem;
use App\Entity\Product;
use App\Entity\User;
use App\Form\AddAddressType;
use App\Repository\AddressRepository;
use App\Repository\OrderItemRepository;
use App\Repository\OrderRepository;
use App\Repository\UserRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class UserPageController extends AbstractController
{
    #[Route('/my-account', name: 'user_page')]
    public function index(OrderItemRepository $orderItemRepository): Response
    {
        if ($this->getUser()) {


            return $this->render('user_page/index.html.twig', [
                'user' => $this->getUser(),
            ]);
        }else{
            return $this->redirectToRoute('app_login');
        }



    }
    #[Route('/my-account/addAddress', name: 'user_addAddress')]
    public function addAdress(Request $request, EntityManagerInterface $entityManager): Response{


        if ($this->getUser()) {

            $address = new Address();

            $form = $this->createForm(AddAddressType::class, $address);
            $form->handleRequest($request);
            if ($form->isSubmitted() && $form->isValid()) {
                $address->setUser($this->getUser());
                $entityManager->persist($address);
                $entityManager->flush();
                return $this->redirectToRoute('user_page');
            }

            return $this->renderForm('user_page/addAddress.html.twig', [
                'user' => $this->getUser(),
                'form' => $form,
            ]);
        }else{
            return $this->redirectToRoute('app_login');
        }

    }


}

templates/user_page/addAddress.html.twig
{% extends 'base.html.twig' %}

{% block title %}{% endblock %}

{% block body %}

<div class="login-box">
    <div class="form-row">
        <h1 class="">Add Address </h1>
    </div>
    {{ form_start(form) }}
    <div class="form-row">
        {{ form_row(form.address_name) }}
        {{ form_row(form.address) }}
    </div>
    <div class="form-row">
        {{ form_row(form.city) }}
        {{ form_row(form.cp) }}
    </div>
    <button class="btn-custom btn-black" type="submit" >Save</button>
    {{ form_end(form) }}
    </div>
{% endblock %}

templates/user_page/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ user.firstName }} {{ user.lastName }}{% endblock %}

{% block body %}


    <section id="page-account" class="content-site">
        <article class="title-section">
            <h2>Account page of {{ user.firstName }} {{ user.lastName }}</h2>
        </article>
        <article>
            <div class="title-classique">
                <h3>Personnal informations</h3>
            </div>
            <aside class="infos-items">
                <p><span style="color: #999999; font-weight: 400;font-style: italic">Nom Prénom : </span> <span style="font-weight: 600">{{ user.lastName}} {{ user.firstName}}</span></p>
                <p><span style="color: #999999; font-weight: 400;font-style: italic">Email : </span> <span style="font-weight: 600">{{ user.email}}</span></p>
            </aside>
            <h3 class="title-classique">Your addresses</h3>
            <aside class="all-box-address">
                {% for address in user.address %}
                    <div class="address-item">
                        <h3>{{ address.addressName }}</h3>
                        <p>{{ address.address }}</p>
                        <p>{{ address.city }}, {{ address.cp }}</p>
                    </div>
                {% endfor %}
                <a class="address-item add-item" href="{{ path('user_addAddress') }}"> <div>
                        <i class="fa-solid fa-plus fa-2x"></i>
                </div></a>
            </aside>


            </aside>
        </article>
        <articles class="orders">
            <section class="title-section">
                <h2>Order(s)</h2>
            </section>

            {% for order in user.orders %}
                <h3 class="title-order">Order numero : {{ order.id }}</h3>
                <div class="shipping">
                    <h4>Shipping address</h4>
                    <p class="title-address">{{ order.address.addressName }}</p>
                    <p>{{ order.address.address }}</p>
                    <p>{{ order.address.city }}{{ order.address.cp }}</p>
                </div>
                <table>
                    <thead>
                        <tr>
                            <td>Product</td>
                            <td>Product image</td>
                            <td>Product Price</td>
                            <td>Status</td>
                        </tr>
                    </thead>
                    <tbody>
                    {% for items in order.orderItems %}

                        <tr>
                            <td style="width: 200px">{{ items.product.name }}</td>
                            <td><a href="{{ path ('product_simple', {id:items.product.id}) }}"> <img style="width: 200px" src="{{ asset('assets/img/products/') }}{{ items.product.img }}"></a></td>
                            <td>{{ items.product.price }}€</td>
                            {% if order.status == "Paid" %}
                                <td style="width: 200px"><span class="status paid">{{ order.status }}</span></td>
                                {% elseif order.status == "In progress" %}
                                    <td style="width: 200px"><span class="status progress">{{ order.status }}</span></td>
                                {% elseif order.status == "Failed" %}
                                    <td style="width: 200px"><span class="status failed">{{ order.status }}</span></td>
                            {% endif %}
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>

                <div class="total-price">

                    <h3>Total order</h3>
                    <span> {{ order.totalPrice }} €</span>

                </div>
                {% endfor %}
    </articles>
    </section>


{% endblock %}